CREATE DATABASE BD;
USE BD;
SHOW TABLES;
CREATE TABLE CIDADE
( 
CÓDIGO INT PRIMARY KEY NOT NULL,
NOME VARCHAR(30) NOT NULL
);

CREATE TABLE SOCIO
(
CPF CHAR(11) PRIMARY KEY NOT NULL,
NOME VARCHAR(30) NOT NULL,
SEXO CHAR(1) NULL CHECK (sexo IN ('M', 'F')),
EMAIL VARCHAR(30) UNIQUE NOT NULL,
CIDADE INT,
FOREIGN KEY (CIDADE) REFERENCES CIDADE
);

CREATE TABLE DEPENDENTE 
(
SOCIO CHAR(11) NOT NULL,
NUMERO INT NOT NULL,
NOME VARCHAR(30) NOT NULL,
PRIMARY KEY (SOCIO, NUMERO),
FOREIGN KEY (SOCIO) REFERENCES SOCIO
)

